// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/obvestila/info": {
            "get": {
                "description": "Returns information about the email service, available templates, and usage instructions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get service information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ServiceInfo"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Returns OK if the service is healthy",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ServiceInfo": {
            "type": "object",
            "properties": {
                "available_templates": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "Email notification service using RabbitMQ and Resend"
                },
                "queue_name": {
                    "type": "string",
                    "example": "emails"
                },
                "service_name": {
                    "type": "string",
                    "example": "obvestila"
                },
                "usage": {
                    "type": "string",
                    "example": "Publish JSON messages to the 'emails' queue"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/obvestila",
	Schemes:          []string{},
	Title:            "Obvestila API",
	Description:      "Email notification service for the PRPO project. Messages are consumed from RabbitMQ queue.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
